### ISSUE TITLE
Lab Report 2 Feedback

### ISSUE THREAD

**Issue by farnaf** [NickHo2048/Lab-Reports#2]
**Bug/Input 1**
- [ ] Commit screenshot for bug/input 1
  - please replace the image with the diff of the code change that fixed bug/input 1 - [something like this](https://github.com/ucsd-cse15l-w22/ucsd-cse15l-w22.github.io/commit/5b427fb733e72e1e396c720cd1a308385a5af5be)
- [x] Link to test file for bug/input 1
- [x] Symptom shown as command + output for bug/input 1
- [x] Description of relationship between bug, symptom, and input for bug/input 1

**Bug/Input 2**
- [ ] Commit screenshot for bug/input 2
  - is not a screenshot of a code change that's a fix for input 2
- [x] Link to test file for bug/input 2
- [x] Symptom shown as command + output for bug/input 2
- [ ] Description of relationship between bug, symptom, and input for bug/input 2
  - doesn't describe the relationship between the bug and the symptom (i.e. wrong output of the program for input 2) correctly

**Bug/Input 3**
- [x] Commit screenshot for bug/input 3
- [ ] Link to test file for bug/input 3
- [ ] Symptom shown as command + output for bug/input 3
- [x] Description of relationship between bug, symptom, and input for bug/input 3

Additional comments from your grader:
nice job 😃 
Feel free to comment below if you have any questions about the rubric/feedback.

--------

If you don't have all the checkmarks above, fix the issues described, and then submit a [regrade request on Gradescope](https://help.gradescope.com/article/8hchz9h8wh-student-regrade-request). Use this template for your regrade request:

- Link to this issue
- Link to your published lab report page

**Comment by NickHo2048** [comment]
I'm confused; what's a commit screenshot. Don't I have a screenshot of the problem that was produced? I also don't understand why I didn't get the point for the link to test file for bug/input 3. There's a link called Test 3, which takes you to it. What counts as "symptom shown as command + output for bug/input 3." Could you please respond as soon as possible; I'm sorry I procrastinated, but I would appreciate all the help I could get.

**Comment by farnaf** [comment]
Hi there, 
- put a screenshot of the diff page of the *changes* you made - I've linked to an example in the above feedback
- Ah I missed Test 3 because it was under Test 2 section
- Don't worry about symptom shown as command + output for bug/input 3, I gave you that requirement (you have total of three but they're in different sections)

**Comment by NickHo2048** [comment]
Oh ok. yea, I'm sorry; I made the page a little disorganized. I reorganized it, but I'm still kinda confused on the first part. We're just putting a screenshot of the code changes, right? I thought I did that under the updated code sections. Could you check again or clarify what I'm doing wrong? 
https://nickho2048.github.io/Lab-Reports/Lab-2/lab-report-2-week-4.html

**Comment by farnaf** [comment]
I think it looks good now! - sorry I seem to have missed the requirements I didn't check because they were ordered differently

Submit a regrade request so i can update your grade
